version: '3'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    restart: always
    security_opt:
      - "no-new-privileges:true"
    environment:
      - TZ=Europe/London
    tty: true
    networks:
      - my-net

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - "no-new-privileges:true"
    environment:
      - TZ=Europe/London
    networks:
      - my-net

  windows:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    container_name: windows
    restart: always
    security_opt:
      - "no-new-privileges:true"
    environment:
      - TZ=Europe/London
    command: ping -t localhost
    networks:
      - my-net

networks:
  my-net:
