version: '3'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/London
    command: tail -f /dev/null

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/London

  windows:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    container_name: windows
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/London
    command: ping -t localhost
